version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
#  BeforeInstall:
#    - location: server_clear.sh
#      timeout: 300
#      runas: ec2-user
#  AfterInstall:
#    - location: fix_privileges.sh
#      timeout: 300
#      runas: ec2-user
  ApplicationStart:
    - location: scripts/server_start.sh
      timeout: 20
      runas: ubuntu
  ApplicationStop:
    - location: scripts/server_stop.sh
      timeout: 20
      runas: ubuntu