version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto17
  pre_build:
    commands:
      - echo Nothing to do in the pre_build phase...
      - mvn test -f pom.xml
  build:
    commands:
      - echo Build started on `date`
      - mvn clean package spring-boot:repackage
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - target/saludtoolsfullstackchallenge-0.0.1-SNAPSHOT.jar